name: "Test Pull Request"

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: Install Firebase
        run: |
          npm install -g firebase-tools
          echo "Installed Firebase version:"
          firebase --version
      - name: Start Firebase Emulator
        run: firebase emulators:start --import=./dir &
      - name: Wait for Firebase Emulator
        run: |
          chmod +x wait.sh
          ./wait.sh
      - name: Set environment
        run: |
          export FIREBASE_DATABASE_EMULATOR_HOST="localhost:9000"
          expopt FIRESTORE_EMULATOR_HOST="localhost:8080"
          export GCLOUD_PROJECT="test"
      - name: Run
        run: node index.js
